name: "Deploy to Vercel"

concurrency:
  cancel-in-progress: false
  group: "vercel"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Cache Node.js modules"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.bun/install/cache
          key: bun-${{ hashFiles('**/bun.lockb') }}

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"

      - name: "Install dependencies"
        run: "bun install --frozen-lockfile"

      - name: "Check code with Biome"
        run: "bun run check"

      - name: "Pull Vercel environment"
        run: "yarn vercel pull --environment=production --token=$VERCEL_TOKEN --yes"

      - name: "Build app using Vercel"
        env:
          NEXT_TELEMETRY_DISABLED: true
        run: "yarn vercel build --prod --token=$VERCEL_TOKEN"

      - name: "Deploy app to Vercel"
        run: "yarn vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN"

      - name: "Add summary"
        run: |
          echo "## Deploy result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
